const config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "outline-variant": "#554434",
        "primary-fixed-dim": "#ffb870",
        "on-tertiary-container": "#444343",
        "surface-tint": "#ffb870",
        "on-primary": "#4a2800",
        "on-background": "#e5e2e1",
        "inverse-primary": "#8b5000",
        "error-container": "#93000a",
        outline: "#a38d7a",
        "on-secondary-container": "#b4b5b5",
        background: "#131313",
        "on-tertiary": "#303030",
        surface: "#131313",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#2f3131",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-surface-variant": "#dbc2ad",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#1b1b1c",
        "surface-container-highest": "#353534",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        secondary: "#c6c6c7",
        "on-primary-fixed": "#2c1600",
        "tertiary-fixed": "#e5e2e1",
        "surface-variant": "#353534",
        tertiary: "#cecbcb",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-container": "#653900",
        "on-primary-fixed-variant": "#693c00",
        "primary-container": "#ff9800",
        primary: "#ffc081",
        "tertiary-container": "#b2b0b0",
        "primary-fixed": "#ffdcbe",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "secondary-container": "#454747",
        "on-error": "#690005",
        "secondary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "48px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "section-gap": "120px",
      },
      fontFamily: {
        "display-lg": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "body-md": ["Inter"],
        "headline-md": ["Montserrat"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
module.exports = config;
